fix: fixed workdlow to track changes and tag correctly.

diff --git a/.github/workflows/generate-changelog.yml b/.github/workflows/generate-changelog.yml
--- a/.github/workflows/generate-changelog.yml
+++ b/.github/workflows/generate-changelog.yml
@@ -27,6 +27,10 @@ jobs:
             echo "No build.gradle or build.gradle.kts file found!"
             exit 1
           fi
+          if [ -z "$APP_VERSION" ]; then
+            echo "Could not extract versionName. Ensure it is defined in build.gradle or build.gradle.kts."
+            exit 1
+          fi
           echo "App version: $APP_VERSION"
           echo "::set-output name=app_version::$APP_VERSION"
 
@@ -40,16 +44,19 @@ jobs:
       - name: Set up SSH
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
+
+      - name: Debug SSH Connection
+        run: ssh -vT git@github.com
 
       - name: Check and Create Tag
         env:
           APP_VERSION: ${{ needs.setup.outputs.app_version }}
         run: |
           # Set remote URL to use SSH
-          git remote set-url origin git@github.com:your-username/your-repo.git
+          git remote set-url origin git@github.com:rikezero/DekTekApp.git
           
           # Fetch existing tags
           git fetch --tags
@@ -75,9 +82,12 @@ jobs:
       - name: Set up SSH
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
+
+      - name: Debug SSH Connection
+        run: ssh -vT git@github.com
 
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
@@ -92,7 +102,7 @@ jobs:
       - name: Generate CHANGELOG.md
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: github_changelog_generator --user your-username --project your-repo -t $GITHUB_TOKEN
+        run: github_changelog_generator --user rikezero --project DekTekApp -t $GITHUB_TOKEN
 
       - name: Commit and Push Changelog
         run: |
